server:
  port: 15001

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/kisdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug